version: '3.7'

services:

  fulfilment-api:
    image: courselabs/fulfilment-api
    ports:
      - "8071:80"
    environment:
      - OPENTRACING_JAEGER_ENABLED=true
      - TRACE_CUSTOM_SPANS=true
      - TRACE_JAEGER_HOST=metrics
    networks:
      - metrics
      - tracing
      - fulfilment 

  fulfilment-authz:
    image: courselabs/fulfilment-authz
    ports:
      - "8072:80"
    environment:
      - Observability__Logging__LogFilePath=logs/fulfilment-authz.json
      - Observability__Metrics__On=true
      - Observability__Trace__Jaeger=true
    volumes:
      - ./config/override.json:/app/config/override.json
      - ./data:/app/logs
    networks:
      - metrics
      - tracing 
      - fulfilment 

  fulfilment-web:
    image: courselabs/fulfilment-web
    ports:
      - "8070:80"
    environment:
      - Observability__Logging__LogFilePath=logs/fulfilment-web.json
      - Observability__Metrics__Enabled=true
      - Observability__Trace__Jaeger=true
      - Observability__Trace__HeaderFormat=B3
      - Documents__Authz__Url=http://fulfilment-authz/check
    volumes:
      - ./config/override.json:/app/config/override.json
      - ./data:/app/logs
    depends_on:
      - fulfilment-api
      - fulfilment-authz
    networks:
      - tracing 
      - fulfilment 

  fulfilment-processor-1:
    image: courselabs/fulfilment-processor
    environment:
      - Observability__Logging__LogFilePath=logs/fulfilment-processor-1.json
      - Observability__StartupDelaySeconds=30
      - Observability__ExitAfterSeconds=120
    volumes:
      - ./config/override.json:/app/config/override.json
      - ./data:/app/logs
    restart: always
    networks: 
      - fulfilment
      - metrics

  fulfilment-processor-2:
    image: courselabs/fulfilment-processor
    environment:
      - Observability__Logging__LogFilePath=logs/fulfilment-2.json
      - Observability__Metrics__Factor=1.5
    volumes:
      - ./config/override.json:/app/config/override.json
      - ./data:/app/logs
    networks: 
      - fulfilment
      - metrics

networks:
  fulfilment:
    name: obsfun-fulfilment
  metrics:
    name: obsfun-metrics
  tracing:
    name: obsfun-tracing