- pipeline.id: fulfilment-processor
  path.config: "/pipelines/fulfilment-processor.conf"

- pipeline.id: fulfilment-web
  path.config: "/pipelines/fulfilment-web.conf"

- pipeline.id: fulfilment-authz
  path.config: "/pipelines/fulfilment-authz.conf"