services:

  fulfilment-api:
    image: courselabs/obsfun-fulfilment-api
    ports:
      - "8071:80"
    environment:
      - OTEL_TRACES_EXPORTER=jaeger
      - TRACE_CUSTOM_SPANS=true
    networks:
      - tracing 
      - fulfilment 

  fulfilment-authz:
    image: courselabs/obsfun-fulfilment-authz
    ports:
      - "8072:80"
    environment:
      - Observability__Trace__Console=false
      - Observability__Trace__Jaeger=true
    networks:
      - tracing 
      - fulfilment 

  fulfilment-web:
    image: courselabs/obsfun-fulfilment-web
    ports:
      - "8070:80"
    environment:
      - Observability__Trace__Console=false
      - Observability__Trace__Jaeger=true
      - Observability__Trace__CustomSpans=true
    depends_on:
      - fulfilment-api
      - fulfilment-authz
    networks:
      - tracing 
      - fulfilment 

networks:
  fulfilment:
  tracing:
    name: obsfun-tracing