version: '3.7'

services:

  fulfilment-processor:
    image: courselabs/fulfilment-processor
    environment:
      - Observability__Logging__Structured=false
      - Observability__Logging__File=true
      - Observability__Logging__Console=false
    volumes:
      - ./data:/app/logs