version: '3.7'

services:

  node-exporter:
    image: courselabs/node-exporter:latest
    build:
      context: ./node-exporter

  prometheus:
    image: courselabs/prometheus:v2.28.1
    build:
      context: ./prometheus

  grafana:
    image: courselabs/grafana:8.0.5
    build:
      context: ./grafana

  jaeger:
    image: courselabs/jaeger:1.24
    build:
      context: ./jaeger