global:
  scrape_interval: 30s

scrape_configs:
  - job_name: 'node-exporter'
    static_configs:
    - targets: ['node-exporter:9100']  
  
  - job_name: 'fulfilment-processor'
    static_configs:
      - targets: ['fulfilment-processor:9110']
      
  - job_name: 'fulfilment-api'
    metrics_path: /actuator/prometheus
    static_configs:
      - targets: ['fulfilment-api']